apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-proxy
  name: kube-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-proxy
  template:
    metadata:
      labels:
        app: kube-proxy
    spec:
      containers:
      - image: registry.cn-shanghai.aliyuncs.com/kube-helm/kube-proxy
        imagePullPolicy: Always
        name: kube-proxy
        env:
        - name: PROXY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
      
